### ISSUE TITLE
[React-Relay]: Smart Subscriptions Plugin with Relay

### ISSUE THREAD

**Issue by baristikir** [hayes/giraphql#100]
I was trying out the `Smart Subscriptions` Plugin on my Express + GraphQL Helix Server together with `graphql-ws` for the websocket connections and was facing some issues on the client side. The subscription works as expected on the `GraphiQL` Playground but fails on the client were I was using `react-relay`.

I tried to debug a bit and this was the output of the `onOperation` from the WebSocket Server. The connection seems alright and this was why I thought it might be related to the plugin.

```bash
    TypeError: Invalid value used as weak map key
        at WeakMap.set (<anonymous>)
        at GiraphQLSmartSubscriptionsPlugin.requestData (/Users/baristikir/tmp/giraphql-relay-subscription/node_modules/@giraphql/core/src/plugins/plugin.ts:160:27)
        at subscribe (/Users/baristikir/tmp/giraphql-relay-subscription/node_modules/@giraphql/plugin-smart-subscriptions/src/index.ts:88:20)
        at /Users/baristikir/tmp/giraphql-relay-subscription/node_modules/graphql/subscription/subscribe.js:177:19
        at new Promise (<anonymous>)
        at executeSubscription (/Users/baristikir/tmp/giraphql-relay-subscription/node_modules/graphql/subscription/subscribe.js:162:10)
        at /Users/baristikir/tmp/giraphql-relay-subscription/node_modules/graphql/subscription/subscribe.js:137:9
        at new Promise (<anonymous>)
        at createSourceEventStream (/Users/baristikir/tmp/giraphql-relay-subscription/node_modules/graphql/subscription/subscribe.js:130:10)
        at subscribeImpl (/Users/baristikir/tmp/giraphql-relay-subscription/node_modules/graphql/subscription/subscribe.js:69:23) {
```

Repository with minimal client-server setup to reproduce the issue:
https://github.com/baristikir/giraphql-relay-subscription

 -> The websocket connection should close after connceting and requesting the subscription data with the same error above.

I'm currently using these versions:
```json
{
	"dependencies": {
		"@giraphql/core": "^2.10.1",
		"@giraphql/plugin-relay": "^2.9.1",
		"@giraphql/plugin-scope-auth": "^2.5.1",
		"@giraphql/plugin-simple-objects": "^2.4.3",
		"@giraphql/plugin-smart-subscriptions": "^2.3.3",
		"@giraphql/plugin-validation": "^2.6.2",
      }
}
```

**Comment by hayes** [comment]
You need to set up your context when using websocket connections. 

You probably want to set up your context properly, but the following will make the error go away:

<img width="744" alt="Screen Shot 2021-07-14 at 1 40 21 PM" src="https://user-images.githubusercontent.com/816527/125690048-805bc2f5-fe14-46fb-b0ea-d57eb165bc37.png">

**Comment by baristikir** [comment]
Thanks alot, that solved my problem. 👍🏻
