### ISSUE TITLE
TypeError: model.slice is not a function

### ISSUE THREAD

**Issue by arnabtarwani** [hayes/giraphql#162]
Experienced this error on the latest version of the Prisma plugin 

```
node_modules/@giraphql/plugin-prisma/src/refs.ts:103
  const lowerCase = `${model.slice(0, 1).toLowerCase()}${model.slice(1)}`;
```

Not sure why this is, as the model is definitely of type string

**Comment by hayes** [comment]
Can you provide a full stack trace?

**Comment by arnabtarwani** [comment]
```
/Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/plugin-prisma/src/refs.ts:103
  const lowerCase = `${model.slice(0, 1).toLowerCase()}${model.slice(1)}`;
                             ^
TypeError: model.slice is not a function
    at getDelegateFromModel (/Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/plugin-prisma/src/refs.ts:103:30)
    at new PrismaObjectFieldBuilder (/Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/plugin-prisma/src/prisma-field-builder.ts:203:41)
    at Object.objectType.fields (/Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/plugin-prisma/src/schema-builder.ts:43:35)
    at /Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/core/src/builder.ts:168:24
    at /Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/core/src/config-store.ts:369:66
    at ConfigStore.onTypeConfig (/Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/core/src/config-store.ts:303:7)
    at ConfigStore.addFields (/Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/core/src/config-store.ts:368:12)
    at /Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/core/src/config-store.ts:366:45
    at /Users/arnabtarwani/Documents/Projects/Zenshops/zenshops/backend/node_modules/@giraphql/core/src/config-store.ts:350:30
    at Array.forEach (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hayes** [comment]
Can't tell for sure where exactly in your app its happening, but you likely have not migrated one of your builder.objectType calls to the new API, and the s still a Prisma delegate.

**Comment by hayes** [comment]
Not sure if you saw that there was a complete API re-design in the latest version.  It now requires adding a generator to your Prisma schema and using strings instead of Prisma delegates

**Comment by arnabtarwani** [comment]
I see, yes I was trying to import prisma delegate, db.user to be exact and I guess that's why it was throwing this error. I'll try to fix it now. Thanks!
